name: kahrp
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.2
  - firelight
  - h5py=3.6.0
  - imageio=2.9.0
  - matplotlib=3.5.1
  - numpy=1.22.3
  - pandas=1.4.2
  - pillow=9.2.0
  - pip=22.1.2
  - python=3.9.12
  - pytorch=1.12.0
  - scikit-image=0.19.2
  - scipy=1.7.3
  - setuptools=63.4.1
  - tifffile=2022.8.12
  - yaml=0.2.5
  - pip:
    - numba==0.55.2
    - opencv-python-headless==4.6.0.66
    - ray==2.0.0
    - requests==2.28.1
    - scikit-learn==1.1.1
    - tqdm==4.64.0
    - cellpose
    - napari[all]
